name: vehicle_monitor_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you plan to publish it

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5

  # Speedometer gauge
  syncfusion_flutter_gauges: ^20.3.58

  # URL launcher (Updated version for bug fixes)
  url_launcher: ^6.2.5

  # Theme/state management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
