name: vehicle_monitor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5

  # Gauge for speedometer
  syncfusion_flutter_gauges: ^20.3.58

  # Theme and state management
  provider: ^6.1.1  # ✅ Added for theme switching support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
